// export default
// [
//   {
//    "id:'1',
//    "img":"https://freepngimg.com/thumb/gym_equipments/41376-6-workout-machine-image-free-download-image.png",
//    "Brand":"Lifelong",
//    "Colour":"Black",
//    "ItemWeight":"2000 Grams",
//    "Material":"PVC",
//    "Maximum_Weight":"2 Kg",
//    "RentperHour":3500,
//    "BookingSlots":[]
//    },
// {
// id:'2',
// "img":"https://freepngimg.com/thumb/gym_equipments/40699-3-gym-equipment-hq-image-free-png.png",
// "Brand":"Livox",
// "Colour":"Multicolor",
// "Material":"	Alloy Steel, Silicone",
// "Item":"MultiColor",
// "ItemWeight":"850 Grams",
// "Maximum_Weight":"180 Kilograms",
// "RentperHour":1500,
// "BookingSlots":[],
// },
// {
// id:'3',
// "img":"https://freepngimg.com/thumb/gym_equipments/40699-3-gym-equipment-hq-image-free-png.png",
// "Brand"	:"Zorex",
// "Colour":"Multicolor",
// "Material":"MS PIPE",
// "ItemWeight":"60 kg",
// "Maximum_Weight":"60kg",
// "RentperHour":1500,
// "BookingSlots":[]
   
// },



// {
// id:'4',
// "img":"https://freepngimg.com/thumb/gym_equipments/40769-3-gym-equipment-png-download-free.png",
// "Brand":"STORE77",
// "Material":"Expanded Polypropylene",
// "Colour":"MultiColor",
// "ItemWeight":"250 Grams",
// "Maximum_Weight":"180 Kilograms",
// "RentperHour":3500,
// "BookingSlots":[]
// },
// {
// id:'5',
// "img":"https://freepngimg.com/thumb/gym_equipments/40710-6-gym-equipment-photos-download-hd-png.png",
// "Brand":"AURION",
// "Colour":"Black",
// "ItemWeight":"20 kg",
// "Material":"Polyvinyl Chloride",
// "Maximum_Weight":"52kg*2",
// "RentperHour":1500,
// "BookingSlots":[]
// },
// {
// id:'6',
// "img":"https://freepngimg.com/thumb/gym_equipments/40825-8-gym-machine-photos-download-hd-png.png",
// "Brand":"Synq.fit",
// "Colour":"Black",
// "Material":"Stainless Steel",
// "ItemWeight":"4100 Grams",
// "Maximum_Weight":"2kg*2",
// "RentperHour":3500,
// "BookingSlots":[],
// },
// {
// id:'7',
// "img":"https://freepngimg.com/thumb/gym_equipments/40774-3-gym-equipment-png-free-photo.png",
// "Brand":"HASHTAG FITNESS",
// "Material":"Alloy Steel",
// "Colour":'Black',
// "Maximum_Weight":"160 Kilograms",
// "ItemWeight":"390 Grams",
// "RentperHour":4500,
// "BookingSlots":[],
// },
// {
// id:'8',
// "img":"https://freepngimg.com/thumb/gym_equipments/40814-4-gym-machine-image-free-hd-image.png",
// "Brand":"V22",
// "Colour":"Black",
// "ItemWeight":"16000 Grams",
// "Material":"Pvc",
// "Maximum_Weight":"16 KG SET",
// "RentperHour":500,
// "BookingSlots":[],
// },
// {
//   id:'9',
//   "img":"https://freepngimg.com/thumb/gym_equipments/40694-8-gym-equipment-image-hd-image-free-png.png",
//   "Brand":"BODI PRO",
//   "Colour":"Black",
//   "Material":"Iron",
//   "ItemWeight":"390 Grams",
//   "Maximum_Weight":"800 Grams",
//   "RentperHour":500,
//   "BookingSlots":[],
// },
// {
//   id:'10',
//   "img":"https://freepngimg.com/thumb/gym_equipments/40694-8-gym-equipment-image-hd-image-free-png.png",
//   "Brand":"The Cube Club",
//   "Colour":"Black",
//   "ItemWeight":"24 Kilograms",
//   "Material":"Plastic",
//   "Maximum_Weight":"24 Kilograms",
//   "RentperHour":3500,
//   "BookingSlots":[],
// },
// {
// id:'11',
// "img":"https://freepngimg.com/thumb/gym_equipments/40758-8-gym-equipment-png-free-photo.png",
// "Brand":"Cloyster",
// "Color":"MultiColor",
// "Material":"Pvc,Rubber",
// "ItemWeight":"200 Grams",
// "Maximum_Weight":"200 Grams",
// "RentperHour":1500,
// "BookingSlots":[],

// },
// {
// id:'12',
// "img":"https://freepngimg.com/thumb/gym_equipments/40684-3-gym-equipment-download-free-hq-image.png",
// "Brand":"HASHTAG FITNESS",
// "ItemWeight":"30 Kilograms",
// "Colour":"Black",
// "Material":"Pvc",
// "Maximum_Weight":"800 Grams",
// "RentperHour":1500,
// "BookingSlots":[],
// }
// ]