export default
[
  {
   id:'1',
   img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/31cHmJmg7mL._SX300_SY300_QL70_FMwebp_.jpg",
   Brand:"Lifelong",
   Colour	:"Black",
   ItemWeight:"2000 Grams",
   Material:"PVC",
   Maximum_Weight:"2 Kg",
   RentperHour :3500,
   BookingSlots:[],
   },
{
id:'2',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/41W-pc7KrHL._SX300_SY300_QL70_FMwebp_.jpg",
Brand:"Livox",
Colour:"Multicolor",
Material:"	Alloy Steel, Silicone",
Item:"Multi",
ItemWeight	:"850 Grams",
Maximum_Weight:"180 Kilograms",
RentperHour :1500,
BookingSlots:[],
},
{
id:'3',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71qsHqCMsnL._SY879_.jpg",
Brand	:"Zorex",
Material	:"MS PIPE",
ItemWeight	:"60 kg",
Maximum_Weight:"60kg",
RentperHour :1500,
BookingSlots:[],
   
},

{
id:'4',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51K0dT0SpEL._AC_UL480_FMwebp_QL65_.jpg",
Brand:"STORE77",
Material:"Expanded Polypropylene",
Colour:"Purple",
ItemWeight:"250 Grams",
Maximum_Weight:"180 Kilograms",
RentperHour :3500,
BookingSlots:[],
},
{
id:'5',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51aUdNyfH7L._SX679_.jpg",
Brand:"AURION",
Colour:"Black",
ItemWeight:"4100 Grams",
Material:"Polyvinyl Chloride",
Maximum_Weight:"2kg*2",
RentperHour :1500,
BookingSlots:[],
},
{
id:'6',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61eCuv86oqL._SX679_.jpg",
Brand	:"Synq.fit",
Colour:"Black",
Material:"Stainless Steel",
ItemWeight:"4100 Grams",
Maximum_Weight:"2kg*2",
RentperHour :3500,
BookingSlots:[],
},
{
id:'7',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51WGxOgHCJL._SX300_SY300_QL70_FMwebp_.jpg",
Brand:"HASHTAG FITNESS",
Material:"Alloy Steel",
Colour:'Black',
Maximum_Weight:"160 Kilograms",
ItemWeight	:"390 Grams",
RentperHour :4500,
BookingSlots:[],
},
{
id:'8',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61WrwJI4gVS._SX679_.jpg",
Brand	:"V22",
Colour:"Black",
ItemWeight:"16000 Grams",
Material:"Pvc",
Maximum_Weight:"16 KG SET",
RentperHour :500,
BookingSlots:[],
},
{
  id:'9',
  img:"https://m.media-amazon.com/images/I/51apeWE-MQL._AC_UL480_QL65_.jpg",
  Brand:"BODI PRO",
  Colour:"Black",
  Material:"Iron",
  ItemWeight	:"390 Grams",
  Maximum_Weight:"800 Grams",
  RentperHour :500,
  BookingSlots:[],
},
{
  id:'10',
  img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71RhgMe6S1L._SX679_.jpg",
  Brand:"The Cube Club",
  Colour:"Black",
  ItemWeight:"24 Kilograms",
  Material:"Plastic",
  Maximum_Weight:"24 Kilograms",
  RentperHour :3500,
  BookingSlots:[],
},
{
id:'11',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51jdvhUK2hL._AC_UL480_FMwebp_QL65_.jpg",
Brand:"Cloyster",
Material:"Pvc,Rubber",
ItemWeight	:"200 Grams",
Maximum_Weight:"200 Grams",
RentperHour :1500,
BookingSlots:[],

},
{
id:'12',
img:"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61OHEn6Al7L._SX679_.jpg",
Brand:"HASHTAG FITNESS",
ItemWeight:"30 Kilograms",
Colour:"Black",
Material:"Pvc",
Maximum_Weight:"800 Grams",
RentperHour :1500,
BookingSlots:[],
}
]